import sys
import json
import os
from datetime import datetime
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QLineEdit, QComboBox, QLineEdit, QCheckBox
import people_operations as po

db = po.PersonDatabase()
people_cpfs = db.get_all_people_names()
names = list(people_cpfs.keys())
cpfs = list(people_cpfs.values())

def showPerson():
    current_name = comboBoxPacientes.currentText()
    current_cpf = people_cpfs[comboBoxPacientes.currentText()]
    person = db.get_person(current_cpf)
    number_procedure = person["last_procedure"]
    label_cpf.setText(current_cpf)
    label_name.setText(current_name)
    label_last_seen.setText(person["last_seen"])
    label_birthday.setText(person["birth_date"])
    label_phone.setText(person["phone"])
    label_number_procedure.setText(f"{number_procedure}")
    btnVerOpc.setText(f"Ver Operações de {comboBoxPacientes.currentText()}")
    label_name_in_procedure.setText(current_name)

def showProcedure():
    cpf = people_cpfs[label_name_in_procedure.text()]
    procedure_id = comboBoxProcedures.currentText()
    procedure_data = db.get_dental_procedure(cpf,procedure_id)
    label_date_in_procedure.setText(f"{procedure_data["date"]}")
    today = datetime.today()
    datem = datetime(today.year, today.month, today.day, today.hour)
    label_date_in_procedure.setText(f"{datem}")
    line_notes_in_procedure.setText(procedure_data["notes"])

def abrir_janela_opcs():
    janelaOperations.setWindowTitle(comboBoxPacientes.currentText())
    janelaOperations.show()
    cpf = people_cpfs[label_name_in_procedure.text()]
    procedures_id = db.get_person_dental_procedures_id(cpf)
    comboBoxProcedures.addItems(procedures_id)
    comboBoxProcedures.setCurrentIndex(int(procedures_id[-1]) - 1)
    showProcedure()
    janelaPessoas.destroy()

def abrir_janela_pacientes():
    janelaPessoas.setWindowTitle("Pacientes do Dr. Sismoto")
    comboBoxProcedures.clear()
    janelaPessoas.show()
    janelaOperations.destroy()



app = QApplication(sys.argv)

janelaPessoas = QWidget()
janelaPessoas.resize(900,500)
janelaPessoas.setWindowTitle("Operações dentais do Dr. Sismoto")

comboBoxPacientes = QComboBox(janelaPessoas)
comboBoxPacientes.addItems(names)
comboBoxPacientes.move(20,40)
comboBoxPacientes.currentIndexChanged.connect(showPerson)

label_paciente = QLabel("Paciente", janelaPessoas)
label_paciente.move(21,10)
label_paciente.setStyleSheet('font-size:20px')

label_name = QLabel("", janelaPessoas)
label_name.move(300,220)
label_name.setStyleSheet('font-size:20px')

label_cpf = QLabel("", janelaPessoas)
label_cpf.move(300,270)
label_cpf.setStyleSheet('font-size:20px')

label_birthday = QLabel("", janelaPessoas)
label_birthday.move(300,320)
label_birthday.setStyleSheet('font-size:20px')

label_last_seen = QLabel("", janelaPessoas)
label_last_seen.move(300,370)
label_last_seen.setStyleSheet('font-size:20px')

label_phone = QLabel("", janelaPessoas)
label_phone.move(300,420)
label_phone.setStyleSheet('font-size:20px')

label_number_procedure = QLabel("", janelaPessoas)
label_number_procedure.move(300,470)
label_number_procedure.setStyleSheet('font-size:20px')

static_label_name = QLabel("Nome: ", janelaPessoas)
static_label_name.move(20,220)
static_label_name.setStyleSheet('font-size:20px')

static_label_cpf = QLabel("CPF", janelaPessoas)
static_label_cpf.move(20,270)
static_label_cpf.setStyleSheet('font-size:20px')

static_label_birthday = QLabel("Dia de nascimento", janelaPessoas)
static_label_birthday.move(20,320)
static_label_birthday.setStyleSheet('font-size:20px')

static_label_last_seen = QLabel("Data ultima consulta", janelaPessoas)
static_label_last_seen.move(20,370)
static_label_last_seen.setStyleSheet('font-size:20px')

static_label_phone = QLabel("Telefone", janelaPessoas)
static_label_phone.move(20,420)
static_label_phone.setStyleSheet('font-size:20px')

static_label_number_procedure = QLabel("Numero de Procedimentos", janelaPessoas)
static_label_number_procedure.move(20,470)
static_label_number_procedure.setStyleSheet('font-size:20px')

btnVerOpc = QPushButton("Ver Operações do paciente", janelaPessoas)
btnVerOpc.setGeometry(400,20,400,50)
btnVerOpc.clicked.connect(abrir_janela_opcs)

#Janela de operações
janelaOperations = QWidget()
janelaOperations.resize(1600,900)

btn3 = QPushButton("Voltar para pacientes", janelaOperations)
btn3.setGeometry(400,20,400,50)
btn3.clicked.connect(abrir_janela_pacientes)

label_name_in_procedure = QLabel("data: ", janelaOperations)
label_name_in_procedure.move(20,10)
label_name_in_procedure.setStyleSheet('font-size:20px')

comboBoxProcedures = QComboBox(janelaOperations)
comboBoxProcedures.move(20,40)
comboBoxPacientes.currentIndexChanged.connect(showProcedure)

fixed_label_date_in_procedure = QLabel("data: ", janelaOperations)
fixed_label_date_in_procedure.move(20,100)
fixed_label_date_in_procedure.setStyleSheet('font-size:20px')

label_notes_in_procedure = QLabel("notes: ", janelaOperations)
label_notes_in_procedure.move(20,250)
label_notes_in_procedure.setStyleSheet('font-size:20px')

today = datetime.today()
datem = datetime(today.year, today.month, today.day, 1)

label_date_in_procedure = QLabel(f"{datem}",janelaOperations)
label_date_in_procedure.move(300,100)
label_date_in_procedure.setStyleSheet('font-size:20px')

line_notes_in_procedure = QLineEdit(janelaOperations)
line_notes_in_procedure.move(300,150)
line_notes_in_procedure.setStyleSheet('font-size:20px')

pixmap_18 = QPixmap('images/18.png')
pixmap_17 = QPixmap('images/17.png')
pixmap_16 = QPixmap('images/16.png')
pixmap_15 = QPixmap('images/15.png')
pixmap_14 = QPixmap('images/14.png')
pixmap_13 = QPixmap('images/13.png')
pixmap_12 = QPixmap('images/12.png')
pixmap_11 = QPixmap('images/11.png')
pixmap_21 = QPixmap('images/21.png')
pixmap_22 = QPixmap('images/22.png')
pixmap_23 = QPixmap('images/23.png')
pixmap_24 = QPixmap('images/24.png')
pixmap_25 = QPixmap('images/25.png')
pixmap_26 = QPixmap('images/26.png')
pixmap_27 = QPixmap('images/27.png')
pixmap_28 = QPixmap('images/28.png')
pixmap_47 = QPixmap('images/47.png')
pixmap_46 = QPixmap('images/46.png')
pixmap_45 = QPixmap('images/45.png')
pixmap_44 = QPixmap('images/44.png')
pixmap_43 = QPixmap('images/43.png')
pixmap_42 = QPixmap('images/42.png')
pixmap_41 = QPixmap('images/41.png')
pixmap_31 = QPixmap('images/31.png')
pixmap_32 = QPixmap('images/32.png')
pixmap_33 = QPixmap('images/33.png')
pixmap_34 = QPixmap('images/34.png')
pixmap_35 = QPixmap('images/35.png')
pixmap_36 = QPixmap('images/36.png')
pixmap_37 = QPixmap('images/37.png')
pixmap_38 = QPixmap('images/38.png')
label_18 = QLabel(janelaOperations)
label_17 = QLabel(janelaOperations)
label_16 = QLabel(janelaOperations)
label_15 = QLabel(janelaOperations)
label_14 = QLabel(janelaOperations)
label_13 = QLabel(janelaOperations)
label_12 = QLabel(janelaOperations)
label_11 = QLabel(janelaOperations)
label_21 = QLabel(janelaOperations)
label_22 = QLabel(janelaOperations)
label_23 = QLabel(janelaOperations)
label_24 = QLabel(janelaOperations)
label_25 = QLabel(janelaOperations)
label_26 = QLabel(janelaOperations)
label_27 = QLabel(janelaOperations)
label_28 = QLabel(janelaOperations)
label_47 = QLabel(janelaOperations)
label_46 = QLabel(janelaOperations)
label_45 = QLabel(janelaOperations)
label_44 = QLabel(janelaOperations)
label_43 = QLabel(janelaOperations)
label_42 = QLabel(janelaOperations)
label_41 = QLabel(janelaOperations)
label_31 = QLabel(janelaOperations)
label_32 = QLabel(janelaOperations)
label_33 = QLabel(janelaOperations)
label_34 = QLabel(janelaOperations)
label_35 = QLabel(janelaOperations)
label_36 = QLabel(janelaOperations)
label_37 = QLabel(janelaOperations)
label_38 = QLabel(janelaOperations)
label_18.setPixmap(pixmap_18)
label_17.setPixmap(pixmap_17)
label_16.setPixmap(pixmap_16)
label_15.setPixmap(pixmap_15)
label_14.setPixmap(pixmap_14)
label_13.setPixmap(pixmap_13)
label_12.setPixmap(pixmap_12)
label_11.setPixmap(pixmap_11)
label_21.setPixmap(pixmap_21)
label_22.setPixmap(pixmap_22)
label_23.setPixmap(pixmap_23)
label_24.setPixmap(pixmap_24)
label_25.setPixmap(pixmap_25)
label_26.setPixmap(pixmap_26)
label_27.setPixmap(pixmap_27)
label_28.setPixmap(pixmap_28)
label_47.setPixmap(pixmap_47)
label_46.setPixmap(pixmap_46)
label_45.setPixmap(pixmap_45)
label_44.setPixmap(pixmap_44)
label_43.setPixmap(pixmap_43)
label_42.setPixmap(pixmap_42)
label_41.setPixmap(pixmap_41)
label_31.setPixmap(pixmap_31)
label_32.setPixmap(pixmap_32)
label_33.setPixmap(pixmap_33)
label_34.setPixmap(pixmap_34)
label_35.setPixmap(pixmap_35)
label_36.setPixmap(pixmap_36)
label_37.setPixmap(pixmap_37)
label_38.setPixmap(pixmap_38)
label_18.move(360,300)
label_17.move(420,300)
label_16.move(480,300)
label_15.move(540,300)
label_14.move(600,300)
label_13.move(660,300)
label_12.move(720,300)
label_11.move(780,300)
label_21.move(840,300)
label_22.move(900,300)
label_23.move(960,300)
label_24.move(1020,300)
label_25.move(1080,300)
label_26.move(1140,300)
label_27.move(1200,300)
label_28.move(1260,300)
label_47.move(360,600)
label_46.move(420,600)
label_45.move(480,600)
label_44.move(540,600)
label_43.move(600,600)
label_42.move(660,600)
label_41.move(720,600)
label_31.move(780,600)
label_32.move(840,600)
label_33.move(900,600)
label_34.move(960,600)
label_35.move(1020,600)
label_36.move(1080,600)
label_37.move(1140,600)
label_38.move(1200,600)

dentes = [18, 17, 16, 15, 14, 13, 12, 11, 21, 22, 23, 24, 25, 26, 27, 28, 48, 47, 46, 45, 44, 43, 42, 41, 31, 32, 33, 34, 35, 36, 37, 38]

checkbox18 = QCheckBox("", janelaOperations)
checkbox17 = QCheckBox("", janelaOperations)
checkbox16 = QCheckBox("", janelaOperations)
checkbox15 = QCheckBox("", janelaOperations)
checkbox14 = QCheckBox("", janelaOperations)
checkbox13 = QCheckBox("", janelaOperations)
checkbox12 = QCheckBox("", janelaOperations)
checkbox11 = QCheckBox("", janelaOperations)
checkbox21 = QCheckBox("", janelaOperations)
checkbox22 = QCheckBox("", janelaOperations)
checkbox23 = QCheckBox("", janelaOperations)
checkbox24 = QCheckBox("", janelaOperations)
checkbox25 = QCheckBox("", janelaOperations)
checkbox26 = QCheckBox("", janelaOperations)
checkbox27 = QCheckBox("", janelaOperations)
checkbox28 = QCheckBox("", janelaOperations)

checkbox47 = QCheckBox("", janelaOperations)
checkbox46 = QCheckBox("", janelaOperations)
checkbox45 = QCheckBox("", janelaOperations)
checkbox44 = QCheckBox("", janelaOperations)
checkbox43 = QCheckBox("", janelaOperations)
checkbox42 = QCheckBox("", janelaOperations)
checkbox41 = QCheckBox("", janelaOperations)
checkbox31 = QCheckBox("", janelaOperations)
checkbox32 = QCheckBox("", janelaOperations)
checkbox33 = QCheckBox("", janelaOperations)
checkbox34 = QCheckBox("", janelaOperations)
checkbox35 = QCheckBox("", janelaOperations)
checkbox36 = QCheckBox("", janelaOperations)
checkbox37 = QCheckBox("", janelaOperations)
checkbox38 = QCheckBox("", janelaOperations)

checkbox18.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox17.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox16.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox15.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox14.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox13.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox12.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox11.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox21.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox22.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox23.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox24.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox25.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox26.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox27.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox28.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox47.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox46.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox45.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox44.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox43.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox42.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox41.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox31.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox32.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox33.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox34.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox35.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox36.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox37.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")
checkbox38.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;}")

checkbox18.move(365,460)
checkbox17.move(425,460)
checkbox16.move(485,460)
checkbox15.move(545,460)
checkbox14.move(605,460)
checkbox13.move(665,460)
checkbox12.move(725,460)
checkbox11.move(785,460)
checkbox21.move(845,460)
checkbox22.move(905,460)
checkbox23.move(965,460)
checkbox24.move(1025,460)
checkbox25.move(1085,460)
checkbox26.move(1145,460)
checkbox27.move(1205,460)
checkbox28.move(1265,460)
checkbox47.move(365,550)
checkbox46.move(425,550)
checkbox45.move(485,550)
checkbox44.move(545,550)
checkbox43.move(605,550)
checkbox42.move(665,550)
checkbox41.move(725,550)
checkbox31.move(785,550)
checkbox32.move(845,550)
checkbox33.move(905,550)
checkbox34.move(965,550)
checkbox35.move(1025,550)
checkbox36.move(1085,550)
checkbox37.move(1145,550)
checkbox38.move(1205,550)

showPerson()
janelaPessoas.show()

app.exec()